# Generated by Django 4.2.4 on 2023-11-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="imageControls",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image1",
                    models.ImageField(
                        blank=True, null=True, upload_to="storeifyworks_cdn"
                    ),
                ),
                ("alt1", models.TextField(blank=True, max_length=120, null=True)),
                ("description1", models.TextField(blank=True, null=True)),
                (
                    "image2",
                    models.ImageField(
                        blank=True, null=True, upload_to="storeifyworks_cdn"
                    ),
                ),
                ("alt2", models.TextField(blank=True, max_length=120, null=True)),
                ("description2", models.TextField(blank=True, null=True)),
                (
                    "image3",
                    models.ImageField(
                        blank=True, null=True, upload_to="storeifyworks_cdn"
                    ),
                ),
                ("alt3", models.TextField(blank=True, max_length=120, null=True)),
                ("description3", models.TextField(blank=True, null=True)),
                (
                    "image4",
                    models.ImageField(
                        blank=True, null=True, upload_to="storeifyworks_cdn"
                    ),
                ),
                ("alt4", models.TextField(blank=True, max_length=120, null=True)),
                ("description4", models.TextField(blank=True, null=True)),
                (
                    "image5",
                    models.ImageField(
                        blank=True, null=True, upload_to="storeifyworks_cdn"
                    ),
                ),
                ("alt5", models.TextField(blank=True, max_length=120, null=True)),
                ("description5", models.TextField(blank=True, null=True)),
                (
                    "image6",
                    models.ImageField(
                        blank=True, null=True, upload_to="storeifyworks_cdn"
                    ),
                ),
                ("alt6", models.TextField(blank=True, max_length=120, null=True)),
                ("description6", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
