# Generated by Django 4.2.4 on 2023-11-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="imageControls",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image1",
                    models.ImageField(
                        blank=True, default="", null=True, upload_to="testing/"
                    ),
                ),
                (
                    "alt1",
                    models.TextField(blank=True, default="", max_length=120, null=True),
                ),
                ("description1", models.TextField(blank=True, default="", null=True)),
                (
                    "image2",
                    models.ImageField(
                        blank=True, default="", null=True, upload_to="testing/"
                    ),
                ),
                (
                    "alt2",
                    models.TextField(blank=True, default="", max_length=120, null=True),
                ),
                ("description2", models.TextField(blank=True, default="", null=True)),
                (
                    "image3",
                    models.ImageField(
                        blank=True, default="", null=True, upload_to="testing/"
                    ),
                ),
                (
                    "alt3",
                    models.TextField(blank=True, default="", max_length=120, null=True),
                ),
                ("description3", models.TextField(blank=True, default="", null=True)),
                (
                    "image4",
                    models.ImageField(
                        blank=True, default="", null=True, upload_to="testing/"
                    ),
                ),
                (
                    "alt4",
                    models.TextField(blank=True, default="", max_length=120, null=True),
                ),
                ("description4", models.TextField(blank=True, default="", null=True)),
                (
                    "image5",
                    models.ImageField(
                        blank=True, default="", null=True, upload_to="testing/"
                    ),
                ),
                (
                    "alt5",
                    models.TextField(blank=True, default="", max_length=120, null=True),
                ),
                ("description5", models.TextField(blank=True, default="", null=True)),
                (
                    "image6",
                    models.ImageField(
                        blank=True, default="", null=True, upload_to="testing/"
                    ),
                ),
                (
                    "alt6",
                    models.TextField(blank=True, default="", max_length=120, null=True),
                ),
                ("description6", models.TextField(blank=True, default="", null=True)),
            ],
            options={
                "verbose_name_plural": "imageControls",
            },
        ),
        migrations.AlterModelOptions(
            name="emailmarketing",
            options={"verbose_name_plural": "emailMarketing"},
        ),
    ]
