# Generated by Django 4.2.4 on 2023-11-25 15:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_imagecontrols"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailmarketing",
            options={"verbose_name_plural": "emailMarketing"},
        ),
        migrations.AlterModelOptions(
            name="imagecontrols",
            options={"verbose_name_plural": "imageControls"},
        ),
    ]
