# Generated by Django 4.2.4 on 2023-11-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_alter_imagecontrols_image1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagecontrols",
            name="image1",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="testing/"
            ),
        ),
        migrations.AlterField(
            model_name="imagecontrols",
            name="image2",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="testing/"
            ),
        ),
        migrations.AlterField(
            model_name="imagecontrols",
            name="image3",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="testing/"
            ),
        ),
        migrations.AlterField(
            model_name="imagecontrols",
            name="image4",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="testing/"
            ),
        ),
        migrations.AlterField(
            model_name="imagecontrols",
            name="image5",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="testing/"
            ),
        ),
        migrations.AlterField(
            model_name="imagecontrols",
            name="image6",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="testing/"
            ),
        ),
    ]
