# Generated by Django 4.2.4 on 2023-11-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_alter_imagecontrols_image1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagecontrols",
            name="alt1",
            field=models.TextField(blank=True, default="", max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="imagecontrols",
            name="alt2",
            field=models.TextField(blank=True, default="", max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="imagecontrols",
            name="alt3",
            field=models.TextField(blank=True, default="", max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="imagecontrols",
            name="alt4",
            field=models.TextField(blank=True, default="", max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="imagecontrols",
            name="alt5",
            field=models.TextField(blank=True, default="", max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="imagecontrols",
            name="alt6",
            field=models.TextField(blank=True, default="", max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="imagecontrols",
            name="description1",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="imagecontrols",
            name="description2",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="imagecontrols",
            name="description3",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="imagecontrols",
            name="description4",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="imagecontrols",
            name="description5",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="imagecontrols",
            name="description6",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
